###############################################################################
# andreagaleazzi.com docker-compose
# Zerbinati Francesco
# 17/01/18
# mariadb + nginx + php
###############################################################################

version: '2'
services:

    mariadb:
      image: mariadb:10
      container_name: mariadb
      restart: always
      volumes:
        - ./mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}

    nginx:
      image: nginx:alpine
      restart: always
      container_name: nginx
      volumes:
          - ./www:/usr/share/nginx/html
          - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./conf/nginx/cloudflare.conf:/etc/nginx/cloudflare.conf
          - ./log/nginx/:/var/log/nginx/
          - ./conf/nginx/sites/default.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "${PORT}:80"

    php:
      build: conf/php-fpm
      restart: always
      container_name: php-fpm
      volumes:
        - ./www:/usr/share/nginx/html
        - ./conf/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini

