###############################################################################
# andreagaleazzi.com docker-compose
# Zerbinati Francesco
# 17/01/18
# mariadb + nginx + php
###############################################################################

version: '2'
services:

    db:
      image: mariadb:10
      container_name: mariadb
      restart: always
      volumes:
        - ./data/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    web-server:
      image: nginx:alpine
      restart: always
      container_name: nginx
      volumes:
          - wordpress:/var/www/html
          - ./data/wordpress/wp-content:/var/www/html/wp-content
          - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./conf/nginx/cloudflare.conf:/etc/nginx/cloudflare.conf
          - ./log/nginx/:/var/log/nginx/
          - ./conf/nginx/sites/default.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "${PORT}:80"

    wordpress-php-fpm:
      image:  wordpress:php7.2-fpm-alpine
      restart: always
      container_name: php-fpm
      volumes:
        - wordpress:/var/www/html
        - ./data/wordpress/wp-config.php:/var/www/html/wp-config.php
        - ./data/wordpress/wp-content:/var/www/html/wp-content
        - ./conf/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini

volumes:
  wordpress: